@Host = http://localhost:3003
@Router = colors

### color 정보 전체 조회
GET {{Host}}/{{Router}}
Content-Type: application/json

### Color 생성
POST {{Host}}/{{Router}}
Content-Type: application/json

{
    "id": "#FFFFFF"
}