@Host = http://localhost:3000
@Router = example-upper

### example-upper 1개 이상 조회
GET {{Host}}/{{Router}}
Content-Type: application/json

# 값이 한 치의 오차도 없이 정확해야 한다.

[
    {
        "id": 3
    },
    {
        "title": "테스트1"
    },
    {
        "defaultDouble": 40
    },
    {
        "id": 111111111
    }
]

### example-upper 1개 이상 생성
POST {{Host}}/{{Router}}
Content-Type: application/json

# 입력 할 행의 컬럼에 1개의 문제라도 존재하면 ORM을 사용한 쿼리가 1개도 실행되지 않음

[
    {
        "title": "제목입니다.",
        "content": "이것은 콘텐츠입니다. 아주 긴 텍스트를 입력할 수 있죠.\n여러 줄도 별 문제 없습니다.\n히히 다음줄"
    },
    {
        "title": "어떤 내용을 입력하고 싶으신가요?",
        "content": "본문을 이 곳에 입력할 수 있습니다.",
        "nullableInt": 30,
        "defaultDouble": 50.2
    }
]


### example-upper 1개 이상 수정
PUT {{Host}}/{{Router}}
Content-Type: application/json

# 조건으로 준 쿼리의 질의 결과가 1개라도 일치하지 않거나, 
# 결과값으로 변경을 원하는 컬럼 명이 다를 경우 ORM을 사용한 쿼리가 실행이 안됨 

{
    "exampleUpperSearchFilters": 
        [
            {
                "title": "제목입니다",
                "defaultDouble": 40
            }
        ],
    "exampleUpperChangeResult": 
        {
            "title": "변경 완료된 제목입니다.",
            "content": "본문!"
        }
}


### example-upper 1개 이상 삭제
DELETE   {{Host}}/{{Router}}
Content-Type: application/json

# 입력 할 행의 컬럼에 1개의 문제라도 존재하면 ORM을 사용한 쿼리가 1개도 실행되지 않음

[
    {
        "title": "제목입니다.",
        "content": "이것은 콘텐츠입니다. 아주 긴 텍스트를 입력할 수 있죠.\n여러 줄도 별 문제 없습니다.\n히히 다음줄"
    }
]