apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
        - name: todo-service
          image: ghcr.io/belf-kr/todo-service/nestjs
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /ping
              port: 3000
            # 웹 서버 시작 전 typeorm 마이그레이션이 오래걸리기 때문에 일정 시간 기달리도록 합니다: 시간 측정 결과 마이그레이션 실행부터 완료까지 약 2분정도 소요되므로 여유있게 2분 30초 기달리도록 합니다 (60 * 2 + 30 = 150)
            initialDelaySeconds: 150
          readinessProbe:
            httpGet:
              path: /ping
              port: 3000
          resources:
            requests:
              cpu: 5m
              memory: 100Mi
            # typeorm 마이그레이션 단계에서만 많은 리소스를 요구하기 때문에 리미트 값이 높게 측정되어 있습니다.
            limits:
              cpu: 100m
              memory: 300Mi
          env:
            # 배포 stages
            - name: STAGES
              valueFrom:
                configMapKeyRef:
                  name: prod-config
                  key: STAGES

            # db master config
            - name: DB_MASTER_HOST
              valueFrom:
                configMapKeyRef:
                  name: prod-config
                  key: DB_MASTER_HOST

            - name: DB_MASTER_PORT
              valueFrom:
                configMapKeyRef:
                  name: prod-config
                  key: DB_MASTER_PORT

            - name: DB_MASTER_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: prod-config
                  key: DB_MASTER_USERNAME

            - name: DB_MASTER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: prod-config
                  key: DB_MASTER_PASSWORD

            - name: DB_MASTER_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: prod-config
                  key: DB_MASTER_DATABASE

            # db slave config
            - name: DB_SLAVE_HOST
              valueFrom:
                configMapKeyRef:
                  name: prod-config
                  key: DB_SLAVE_HOST

            - name: DB_SLAVE_PORT
              valueFrom:
                configMapKeyRef:
                  name: prod-config
                  key: DB_SLAVE_PORT

            - name: DB_SLAVE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: prod-config
                  key: DB_SLAVE_USERNAME

            - name: DB_SLAVE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: prod-config
                  key: DB_SLAVE_PASSWORD

            - name: DB_SLAVE_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: prod-config
                  key: DB_SLAVE_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: todo-service
