apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
  namespace: qa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
        - name: todo-service
          image: ghcr.io/belf-kr/todo-service/nestjs
          ports:
            - containerPort: 3000
          env:
            - name: STAGES
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: STAGES
            # MASTER
            - name: DB_MASTER_HOST
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_MASTER_HOST

            - name: DB_MASTER_PORT
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_MASTER_PORT

            - name: DB_MASTER_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_MASTER_USERNAME

            - name: DB_MASTER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_MASTER_PASSWORD

            - name: DB_MASTER_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_MASTER_DATABASE
            # SLAVE
            - name: DB_SLAVE_HOST
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_SLAVE_HOST

            - name: DB_SLAVE_PORT
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_SLAVE_PORT

            - name: DB_SLAVE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_SLAVE_USERNAME

            - name: DB_SLAVE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_SLAVE_PASSWORD
                  
            - name: DB_SLAVE_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_SLAVE_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: qa
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: todo-service
