apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
  namespace: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
        - name: todo-service
          image: ghcr.io/belf-kr/todo-service/nestjs
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 5m
              memory: 100Mi
            # typeorm 마이그레이션 단계에서만 많은 리소스를 요구하기 때문에 리미트 값이 높게 측정되어 있습니다.
            limits:
              cpu: 100m
              memory: 300Mi
          env:
            # 배포 stages
            - name: STAGES
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: STAGES

            # db master config
            - name: DB_MASTER_HOST
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_MASTER_HOST

            - name: DB_MASTER_PORT
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_MASTER_PORT

            - name: DB_MASTER_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_MASTER_USERNAME

            - name: DB_MASTER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_MASTER_PASSWORD

            - name: DB_MASTER_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_MASTER_DATABASE

            # db slave config
            - name: DB_SLAVE_HOST
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_SLAVE_HOST

            - name: DB_SLAVE_PORT
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_SLAVE_PORT

            - name: DB_SLAVE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_SLAVE_USERNAME

            - name: DB_SLAVE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_SLAVE_PASSWORD

            - name: DB_SLAVE_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: DB_SLAVE_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: qa
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: todo-service
