apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
        - name: todo-service
          image: ghcr.io/belf-kr/todo-service/nestjs
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: todo-service
