apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-server
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-server
  template:
    metadata:
      labels:
        app: front-server
    spec:
      containers:
        - name: front-server
          image: ghcr.io/belf-kr/front-server/nextjs
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: front-server
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: front-server
