@Host = http://localhost:3003
@Router = course

### course 1개 이상 조회
GET {{Host}}/{{Router}}
Content-Type: application/json

[
    {
        "name": "test name",
        "exampleUpperId": 1
    },
    {
        "exampleUpperId": 1
    }
]

### course 1개 이상 생성
POST {{Host}}/{{Router}}
Content-Type: application/json

[
    {
        "color": "#FF8484",
        "title": "영어공부하기",
        "explanation": "토익 ..."
    }
]


### course 1개 이상 수정
PUT {{Host}}/{{Router}}
Content-Type: application/json

{
    "crudEntitySearchFilters": 
    [
        {
            "id": 3
        },
        {
            "name": "This is name 1 from http"
        }
    ],
    "crudChangeResult": 
    {
        "name": "This is modified name from http"
    }
}


### course 1개 이상 삭제
DELETE   {{Host}}/{{Router}}
Content-Type: application/json

[
    {
        "id": 1
    },
    {
        "name": "test name2"
    }
]

# API
### course 1개 이상 삽입
POST {{Host}}/{{Router}}/create-course
Content-Type: application/json

{
    "color": "#FF8484",
    "title": "영어공부하기",
    "explanation": "토익 ...",
    "tags": [
        {
            "value": "영어"
        },
        {
            "value": "토익"
        }
    ]
}