@Host = http://localhost:3003
@Router = courses

### course 리스트 조회
GET {{Host}}/{{Router}}?userId=

### course 생성
POST {{Host}}/{{Router}}
Content-Type: application/json

{
    "color": "#FF8484",
    "title": "영어공부하기1",
    "explanation": "토익 ...",
    "tags": [
        {
            "value": "자동차"
        },
        {
            "value": "하하하"
        }
    ],
    "creatorId": 1
}

### course 삭제
DELETE {{Host}}/{{Router}}/courses/1?userId=