@Host = http://localhost:3003
@Router = work-todo

### work_todo 추가
POST {{Host}}/{{Router}}/create-work-todo
Content-Type: application/json

{
    "courseId": 1,
    "recurringCycleDate": 1,
    "title": "나만의 할 일",
    "explanation": "나만의 할 일 설명",
    "passedDay": 5
}