@Host = http://localhost:3003
@Router = work-todos

### work_todo 추가(필수)
POST {{Host}}/{{Router}}
Content-Type: application/json

{
    "courseId": 1,
    "title": "나만의 할 일3"
}

### work_todo 추가(선택)
POST {{Host}}/{{Router}}
Content-Type: application/json

{
    "courseId": 1,
    "recurringCycleDate": 1,
    "title": "나만의 할 일1",
    "explanation": "나만의 할 일 설명1",
    "activeDate": "2021-11-05T08:50:00.12"
}

### work_todo 전체 리스트 가져오기
GET {{Host}}/{{Router}}?courseId=1

### work_todo 삭제
DELETE {{Host}}/{{Router}}/1
Content-Type: application/json