@Host = http://localhost:3003
@Router = work-todos

### work_todo 추가
POST {{Host}}/{{Router}}
Content-Type: application/json

{
    "courseId": 65,
    "recurringCycleDate": 1,
    "title": "나만의 할 일3",
    "explanation": "나만의 할 일 설명3",
    "passedDay": 5
}

### work_todo 전체 리스트 가져오기
GET {{Host}}/{{Router}}
Content-Type: application/json

### work_todo 삭제
DELETE {{Host}}/{{Router}}/work-todos/1
Content-Type: application/json