@Host = http://localhost:3003
@Router = work-dones

### work_done 추가
POST {{Host}}/{{Router}}
Content-Type: application/json

{
    "workTodoId": 6,
    "title": "한 일의 제목1",
    "content": "json 컨텐츠 1"
}

### work_done 전체 리스트 가져오기
GET {{Host}}/{{Router}}

### work_done 리스트 가져오기
GET {{Host}}/{{Router}}?courseId=1

### work_done 1개 가져오기
GET {{Host}}/{{Router}}/1

### work_done 삭제
DELETE {{Host}}/{{Router}}/1